import type { Metadata } from 'next'
import './globals.css'
import Navigation from '@/components/organisms/Navigation/Component'
import Footer from '@/components/organisms/Footer/Component'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-poppins'>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
