import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/organisms/Navigation/Component";
import Footer from "@/components/organisms/Footer/Component";
import "../fontawesome";
import DefaultMetatags from "@/components/molecules/DefaultMetatags/Component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="static h-auto">
      <DefaultMetatags />
      <body className="font-commons mr-0 bg-navy text-white">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
