import type { Metadata } from 'next';
import './globals.css';
import Navigation from '@/components/organisms/Navigation/Component';
import Footer from '@/components/organisms/Footer/Component';
import '../fontawesome';
import DefaultMetatags from '@/components/molecules/DefaultMetatags/Component';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden scroll-smooth">
      <DefaultMetatags />
      <body className="font-roboto m-0 bg-primary text-white overflow-x-hidden relative">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
